### ISSUE TITLE
Incorrect syntax for vendor:publish in readme

### ISSUE THREAD

**Issue by clarkewing** [Naoray/laravel-reviewable#14]
Hey there,

Great package! However it seems there may be a small error in the readme, spend about 15 minutes scratching my head about this one!

The readme _**should read**_ `php artisan vendor:publish --provider="Naoray\LaravelReviewable\LaravelReviewableServiceProvider"`. The double quotes were missing around the Service Provider's path, preventing the command from functioning correctly.

Additionally, you may want to specify the command is also required to publish the migration.

Thanks for the great package!

**Comment by Naoray** [comment]
@clarkewing thanks for pointing it out! Have fixed it now :)
