### ISSUE TITLE
unsinged should be unsigned

### ISSUE THREAD

**Issue by philipgunther** [Naoray/laravel-reviewable#2]
https://github.com/Naoray/laravel-reviewable/blob/b4caaf5f3766b347e92972afe6645d1bb6a6a263/database/migrations/create_reviews_table.php.stub#L20

Great repo! Just a typo I've found. Should be "unsigned" :)

**Comment by Naoray** [comment]
Thanks! Strange that the tests didn't pick up on this :thinking:

**Comment by philipgunther** [comment]
Can you do me a small favor and delete or update my former handle/username in your previous message so that this string will not be found in Google? Thanks!

**Comment by Naoray** [comment]
Done
